[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.17"

[features]
resolution = true
skip-lint = false

[programs.localnet]
ppv_core = "Dkujj5vZp8kxhqM6hQTqqV3sTQ4Rx7J77No4bfwjrfXp"
ppv_commerce = "4Y83YzUZnJ5LF9M1PcKHtsYcQ1LRxedwDi93PVf5H1FJ"
ppv_governance = "HMMsMHi749qo5sBQY49Ttu3KKNQ7XPhK5nZAGYPTygyr"

[programs.devnet]
ppv_core = "Dkujj5vZp8kxhqM6hQTqqV3sTQ4Rx7J77No4bfwjrfXp"
ppv_commerce = "4Y83YzUZnJ5LF9M1PcKHtsYcQ1LRxedwDi93PVf5H1FJ"
ppv_governance = "HMMsMHi749qo5sBQY49Ttu3KKNQ7XPhK5nZAGYPTygyr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test:anchor"
